/*
    Generated by generate_version.sh @ Sun Jan  4 10:20:19 UTC 2026
*/

using System.Reflection;

// Main versioning. Debug versions are constant.

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyInformationalVersion("1.0.0+DEBUG")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
#else
#if PUBLIC_DEBUG
[assembly: AssemblyInformationalVersion("2.2.3+PublicDebug.20260104.463a5d7")]
[assembly: AssemblyConfiguration("PublicDebug")]
#else
[assembly: AssemblyInformationalVersion("2.2.3+Release.20260104.463a5d7")]
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyVersion("2.2.3")]
[assembly: AssemblyFileVersion("2.2.3")]
#endif

[assembly: AssemblyCompany("APKognito")]
[assembly: AssemblyProduct("APKognito")]
[assembly: AssemblyTitle("APKognito")]
[assembly: System.Runtime.Versioning.TargetPlatform("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform("Windows7.0")]
